name: Drizzle Migrate

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/server/src/db/**"
      - "apps/server/drizzle.config.ts"

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run migrations
        env:
          POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
          NODE_ENV: production
        run: |
          pnpm -C apps/server drizzle-kit generate
          pnpm -C apps/server drizzle-kit migrate
